// This file is generated by Sapper — do not edit it!
export const timestamp = 1540398865190;

export const assets = [
	"favicon.png",
	"global.css",
	"logo-192.png",
	"logo-512.png",
	"logo-dark.svg",
	"logo-light.svg",
	"manifest.json"
];

export const shell = [
	"client/754b07474c075d275861/wifi.0.js",
	"client/754b07474c075d275861/redirect.1.js",
	"client/754b07474c075d275861/_.2.js",
	"client/754b07474c075d275861/_5xx.3.js",
	"client/754b07474c075d275861/_4xx.4.js",
	"client/754b07474c075d275861/main.js"
];

export const routes = [
	
];