// This file is generated by Sapper — do not edit it!
import _4xx0 from '../../routes/4xx.html';
import _5xx0 from '../../routes/5xx.html';
import _0 from '../../routes/index.html';
import redirect0 from '../../routes/redirect.html';
import wifi0 from '../../routes/wifi.html';

export const routes = [
	{ error: '4xx', handlers: [{ type: 'page', module: _4xx0 }] },
	{ error: '5xx', handlers: [{ type: 'page', module: _5xx0 }] },
	{ id: '_', pattern: /^\/?$/, params: () => ({}), handlers: [{ type: 'page', module: _0 }] },
	{ id: 'redirect', pattern: /^\/redirect\/?$/, params: () => ({}), handlers: [{ type: 'page', module: redirect0 }] },
	{ id: 'wifi', pattern: /^\/wifi\/?$/, params: () => ({}), handlers: [{ type: 'page', module: wifi0 }] }
];